tools/frontend/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('dbpedia_links_rating.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Rating
    url(r'^rating/', include('dbpedia_links_rating.rating.urls', namespace='rating')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

tools/frontend/dbpedia_links_rating/rating/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

app_name = 'rating'

urlpatterns = [

    url(
        regex = r'^$',
        view = views.RatingView.as_view(),
        name = 'rating'),
]

tools/frontend/dbpedia_links_rating/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

tools/frontend/dbpedia_links_rating/rating/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import, print_function
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from dbpedia_links_rating.users.models import User

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from random import randint
from django.db.models.aggregates import Count


@python_2_unicode_compatible
class Link(models.Model):
    subject = models.CharField(max_length=200)
    object = models.CharField(max_length=200)
    predicate = models.CharField(max_length=200)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.subject + " -- " + self.predicate + " -- " + self.object + " -- " + str(self.score)

    @staticmethod
    def randomComplete():
        count = Link.objects.count()
        #count = Link.aggregate(count=Count('id'))['count']
        random_index = randint(0, count - 1)
        return Link.objects.all()[random_index]

    @staticmethod
    def randomNotRated(request):
        count = Link.objects.exclude(rating__user=request.user).count()
        if count > 0:
            random_index = randint(0, count - 1)
            return Link.objects.exclude(rating__user=request.user)[random_index]
        else:
            return None



@python_2_unicode_compatible
class Rating(models.Model):
    link = models.ForeignKey(Link, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    RATING = (
        (-1, 'No'),
        (0, 'Unsure'),
        (1, 'Yes'),
    )
    rating = models.IntegerField(default=0, choices=RATING)

    def __int__(self):
        return self.rating


@python_2_unicode_compatible
class File(models.Model):
    file = models.FileField(upload_to='links/%Y/%m/%d')

tools/frontend/dbpedia_links_rating/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

tools/frontend/dbpedia_links_rating/rating/forms.py
from django import forms

RANGES = [
    ('-1', 'No'),
    ('0', 'Unsure'),
    ('1', 'Yes'),
]


class CreateRatingForm(forms.Form):
    rating = forms.ChoiceField(widget=forms.RadioSelect, choices=RANGES)

tools/frontend/dbpedia_links_rating/rating/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.views.generic import TemplateView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction

from django.contrib import messages
from django.shortcuts import redirect

from .models import Link, Rating
from .forms import CreateRatingForm

class RatingView(LoginRequiredMixin, TemplateView):
    template_name = 'rating/rating_index.html'
    model = Link

    def post(self, request, *args):
        return self.create(request)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request=request)
        return super(TemplateView, self).render_to_response(context)

    def get_context_data(self, **kwargs):
        #context = super(RatingView, self).get_context.data(**kwargs)
        context = {}
        if 'request' in kwargs:
            context['link'] = Link.randomNotRated(kwargs['request'])
        context['form'] = CreateRatingForm()
        return context

    def create(self, request):
        link_id = int(request.POST.get('link_id'))
        return_url = request.POST.get('return_url')
        try:
            with transaction.atomic():
                # Current user HAS rated this object
                # Updates his rating and total score
                rating = Rating.objects.get(user=request.user, link_id=link_id )
                rating.rating = request.POST.get('rating')
                rating.save()

                #ratings = Rating.objects.filter(link_id = link_id).all()
                link = Link.objects.get(id=link_id)
                link.score += int(request.POST['rating'])
                link.save()
                messages.success(request, 'Score updated succesfully')
        except Rating.DoesNotExist:
            # Current user has NOT rated this object
            # Saves first new rating

            with transaction.atomic():
                Rating.objects.create(rating=request.POST['rating'], link_id=link_id, user=request.user)
                link = Link.objects.get(id=link_id)
                link.score += int(request.POST['rating'])
                link.save()
                messages.success(request, 'Score updated succesfully')

        return redirect(return_url)

tools/frontend/dbpedia_links_rating/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

tools/frontend/dbpedia_links_rating/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}DBpedia-Links Rating{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
        <!-- Latest compiled and minified Bootstrap 4 Alpha 3 CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css"
              integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY"
              crossorigin="anonymous">

        <!-- Your stuff: Third-party CSS libraries go here -->

        <!-- This file stores project-specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

</head>

<body>

<div class="m-b-1">
    <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
            <a class="navbar-brand hvr-underline-from-left" href="/">DBpedia-Links Rating</a>
            <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse"
                    data-target="#bs-navbar-collapse-1">
                &#9776;
            </button>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="nav-item hvr-underline-from-left">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item hvr-underline-from-left">
                            <a class="nav-link" href="{% url 'rating:rating' %}">Rate Links</a>
                        </li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav pull-xs-right">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item hvr-underline-from-left">
                            <a class="nav-link"
                               href="{% url 'users:detail' request.user.username %}">{% trans user.username %}</a>
                        </li>
                        <li class="nav-item hvr-underline-from-left">
                            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign out" %}</a>
                        </li>
                    {% else %}
                        <li class="nav-item hvr-underline-from-left">
                            <a id="sign-up-link" class="nav-link"
                               href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                        </li>
                        <li class="nav-item hvr-underline-from-left">
                            <a id="log-in-link" class="nav-link"
                               href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="container">

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- Required by Bootstrap v4 Alpha 3 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"
            integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"
            integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js"
            integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD"
            crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
</body>
</html>